// Generated by CoffeeScript 1.6.3
var should, understory;

should = require('chai').should();

understory = require('../understory');

describe('understory', function() {
  return describe('#rm_prefix', function() {
    it('Removes a string from the left of another. Removes leading slash by default.', function() {
      return understory.rm_prefix('/some/long/path', '/some').should.equal('long/path');
    });
    return it('Only remove subject string. Not leading slash', function() {
      return understory.rm_prefix('/some/long/path', '/some', false).should.equal('/long/path');
    });
  });
});
