// Generated by CoffeeScript 1.6.3
var path, understory, _;

path = require('path');

_ = require('lodash');

_.str = require('underscore.string');

_.mixin(_.str.exports());

understory = {
  rm_prefix: function(full_str, prefix, strip_slash) {
    if (strip_slash == null) {
      strip_slash = true;
    }
    if (full_str.substring(0, prefix.length) === prefix) {
      full_str = full_str.substring(prefix.length);
      if (strip_slash && '/' === full_str.substring(0, 1)) {
        full_str = full_str.substring(1);
      }
    }
    return full_str;
  },
  dir_i: function(dirname_str) {
    var ret_val,
      _this = this;
    if (!_.isString(dirname_str)) {
      return false;
    }
    if (dirname_str === '.') {
      return false;
    }
    ret_val = {
      dirsplit: dirname_str.split(path.sep)
    };
    _.forEach(ret_val.dirsplit, function(dir, i) {
      return ret_val["dir" + (i + 1)] = dir;
    });
    return ret_val;
  }
};

_.mixin(path);

_.mixin(understory);

module.exports = _;
