// Generated by CoffeeScript 1.6.3
var hogan, path, understory, _;

path = require('path');

_ = require('lodash');

_.str = require('underscore.string');

_.mixin(_.str.exports());

hogan = require('hogan');

understory = {
  rm_prefix: function(full_str, prefix, strip_slash) {
    if (strip_slash == null) {
      strip_slash = true;
    }
    if (full_str.substring(0, prefix.length) === prefix) {
      full_str = full_str.substring(prefix.length);
      if (strip_slash && '/' === full_str.substring(0, 1)) {
        full_str = full_str.substring(1);
      }
    }
    return full_str;
  },
  dir_i: function(dirname_str) {
    var ret_val,
      _this = this;
    if (!_.isString(dirname_str)) {
      return false;
    }
    if (dirname_str === '.') {
      return false;
    }
    ret_val = {
      dirsplit: dirname_str.split(path.sep)
    };
    _.forEach(ret_val.dirsplit, function(dir, i) {
      return ret_val["dir" + (i + 1)] = dir;
    });
    return ret_val;
  },
  token_replace: function(t, vars) {
    var _this = this;
    if (!_.isObject(vars)) {
      console.log('NO vars sent to token_replace');
      return t;
    }
    if (_.isObject(t)) {
      t = _.mapValues(t, function(str) {
        if (_.isString(str)) {
          return hogan.compile(str).render(vars);
        } else if (_.isObject(str)) {
          return _.token_replace(str, vars);
        } else {
          return str;
        }
      });
    } else if (_.isString(t)) {
      t = hogan.compile(t).render(vars);
    } else {
      console.log('NOT A STRING OR OBJECT for t in token_replace()');
      console.log(t);
      console.log(vars);
    }
    return t;
  },
  string_replace: function(info) {
    var re, string;
    string = info.string;
    if (!string) {
      return null;
    }
    if (info.toUpperCase) {
      string = string.toUpperCase();
    }
    if (info.split_on) {
      string = string.split(info.split_on);
      _.forEach(string, function(value, i) {
        if (info.trim) {
          value = _.str.trim(value);
        }
        if (info.find_replace[value]) {
          return string[i] = info.find_replace[value];
        }
      });
    } else {
      if (info.regex) {
        if (!info.regex_options) {
          info.regex_options = "g";
        }
        re = new RegExp(info.regex, info.regex_options);
        string = string.replace(re, info.replace);
      } else if (_.isObject(info.find_replace)) {
        _.forEach(info.find_replace, function(new_value, old_value) {
          return string = string.replace(old_value, new_value);
        });
      } else if (info.find && info.replace) {
        string = string.replace(info.find, info.replace);
      }
    }
    return string;
  },
  last_dash: function(str) {
    return _.last(str.split('-'));
  }
};

_.mixin(path);

_.mixin(understory);

module.exports = _;
